export enum OrderStatus {
    EM_PROCESSAMENTO = "EM_PROCESSAMENTO",
    APROVADO = "APROVADO",
    EM_TRANSITO = "EM_TRANSITO",
    ENTREGUE = "ENTREGUE",
    CANCELADO = "CANCELADO",
    PAGAMENTO_REPROVADO = "PAGAMENTO_REPROVADO",
}